### ISSUE TITLE
сломалось переименовывание при экспорте

### ISSUE THREAD

**Issue by panic70** [petrovvlad/freeLib#130]
После какого то из последних обновлений сломалось переименовывание по шаблону.
В настройках стоит шаблон "%nl%fi - %s%n2 - %b", при экспорте выдаёт что то типа "1lM. - Skidbladnir Online12 - Krov i zhizn.fb2", а должно быть "KuzminM. - Skidbladnir Online01 - Krov i zhizn.fb2", на книжках без серии выдаёт "KuzminM. - %n2 - Richashie Psi.fb2", на книжках без серии с номером тома "6lM. - 62 - Uterjannie krilja.fb2"
Система Gentoo, freelib собран самописным ебилдом Clang-16
До недавнего времени всё экспортировалось нормально.

**Comment by panic70** [comment]
Проверил, у меня заработало. Единственное по экспорту вопрос давно возник, сейчас при выводе инициала добавляется точка, которая ИМХО не нужна, нельза ли поведение поменять и выводить без точки, а кому точка всё же нужна - может добавить её в шаблоне.

**Comment by panic70** [comment]
Это просто скобки? Или они, как в foobar2000, выполняют функции условия (если значение пустое - всё что в скобках опускается и не выводится)?

**Comment by petrovvlad** [comment]
Выполняют функцию условия.
