### ISSUE TITLE
Support zip in zip

### ISSUE THREAD

**Issue by gaydenko** [petrovvlad/freeLib#135]
Some libs contain a set of zip files, adn each of them contains another zip files, and the last ones are just zipped fb2. It would be great to support this case.

**Comment by gaydenko** [comment]
Sorry, I must add that console error message are for current git master.

**Comment by ukcuk** [comment]
So, adding zip"n"zip is still in development?

**Comment by petrovvlad** [comment]
Yes.

**Comment by petrovvlad** [comment]
Added support for zip in zip d374c66. Test it please.

**Comment by ukcuk** [comment]
wow, I'll test it tomorrow, thanks for your advice!

**Comment by gaydenko** [comment]
> Added support for zip in zip [d374c66](https://github.com/petrovvlad/freeLib/commit/d374c66477ec84e93860bf089adeb5cda969e4b0). Test it please.

You did, sincerely thanks. Have tried true scan without index file using.

**Comment by ukcuk** [comment]
and, it's working! big thanks
