### ISSUE TITLE
перестал собираться

### ISSUE THREAD

**Issue by panic70** [petrovvlad/freeLib#136]
Что то недано поменялось? Вроде не так давно всё нормально собиралось, сейчас выдаёт ошибку.
[build.log](https://github.com/petrovvlad/freeLib/files/13932796/build.log)

**Comment by petrovvlad** [comment]
Последние изменения были 3 месяца назад :(. 
У меня собирается без ошибок. Что у Вас обновлялось, что может повлиять на сборку?

**Comment by panic70** [comment]
Трудно сказать. Gentoo такой дистр, что в нём постоянно что-то меняется. На днях обновил шланга до версии 17.0.6, но за день до этого на предыдущей версии 16.0.6 тоже не собралось, хотя буквально месяц назад на том же 16 шланге всё собиралось.
Есди нужно больше инфы по окружению - предоставлю :-)

**Comment by petrovvlad** [comment]
`ninja: build stopped: subcommand failed.`
Возможно что то поменялось в Ninja.

**Comment by panic70** [comment]
Вроде бы никаких настроек сборки не менялось, да и ошибка там не в нинзе, выше в логе ругается на что-то Qt'шное
In file included from /var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.cpp:2:
/var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.h:33:33: error: allocation of incomplete type 'QToolButton'
   33 |         QToolButton *button=new QToolButton(frame);
      |                                 ^~~~~~~~~~~
/usr/include/qt5/QtWidgets/qlineedit.h:61:7: note: forward declaration of 'QToolButton'
   61 | class QToolButton;
      |       ^
In file included from /var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.cpp:2:
/var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.h:34:15: error: member access into incomplete type 'QToolButton'
   34 |         button->setText(QStringLiteral("..."));
      |               ^
/usr/include/qt5/QtWidgets/qlineedit.h:61:7: note: forward declaration of 'QToolButton'
   61 | class QToolButton;
      |       ^
In file included from /var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.cpp:2:
/var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.h:37:27: error: cannot initialize a parameter of type 'QWidget *' with an lvalue of type 'QToolButton *'
   37 |         layout->addWidget(button,0);
      |                           ^~~~~~
/usr/include/qt5/QtWidgets/qlineedit.h:61:7: note: 'QToolButton' is not defined, but forward declared here; conversion would be valid if it was derived from 'QWidget'
   61 | class QToolButton;
      |       ^
/usr/include/qt5/QtWidgets/qboxlayout.h:74:29: note: passing argument to parameter here
   74 |     void addWidget(QWidget *, int stretch = 0, Qt::Alignment alignment = Qt::Alignment());
      |                             ^
In file included from /var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.cpp:2:
/var/tmp/portage/app-text/freelib-9999/work/freelib-9999/freeLib/src/settingsdlg.h:42:26: error: use of undeclared identifier 'QAbstractButton'

**Comment by petrovvlad** [comment]
Не может быть проблемы со свободной RAM?

**Comment by panic70** [comment]
Рамы 16гиг, практически незаюзанной + динамически подстёгиваемый свап, как бы более тяжёлые проекты без проблем собираются.

**Comment by panic70** [comment]
Хм, странно, кажись пакетный менеджер чудит.
Сейчас зашёл в каталог с исходниками, вручную ввел команду из инструкции - собралось.
В ебилде всё практически то же самое - не собирается, буду разбираться.
