### ISSUE TITLE
Kindlegen executable in repo

### ISSUE THREAD

**Issue by faveoled** [petrovvlad/freeLib#138]
Hello,
What is kindlegen and why is it in the repo in binary form? Also is it GPL-3?

**Comment by petrovvlad** [comment]
Kindlegen - cli tool to build eBooks that can be used on Amazon’s Kindle platform.
What's better? Remove the binary from the package or change the license?

**Comment by faveoled** [comment]
Is download on first run possible?

**Comment by petrovvlad** [comment]
Yes, but I do not like it.

**Comment by faveoled** [comment]
GitHub repos should not contain executables. Maybe use Releases section for this (assuming kindlegen has no problem with redistribution policy)

**Comment by petrovvlad** [comment]
bf7e1b52af79b8d83c8213fd8c18175efaaf5012 Kindlegen removed from repository.
