### ISSUE TITLE
Library dialog doens't close

### ISSUE THREAD

**Issue by gaydenko** [petrovvlad/freeLib#142]
Not sure if the problem is related to #135  

After adding a new library the Add/Edit Library dialog can not be close nor with button, nor with window decoration `x` icon. Up to date EndeviourOS is in use (in fact it is based on Arch repo, that is all packages mostly are the last upstream stable ones).

**Comment by petrovvlad** [comment]
Fix 6a705dd9d7f616726080b3c88e54925800ef0b86 bug. Check please.

**Comment by gaydenko** [comment]
freeLib - Version 6.0.84
Revision: 18f3b9f

Unfortunately opened library dialog still can not be closed.
