### ISSUE TITLE
Не запускается на KDE 6

### ISSUE THREAD

**Issue by bazilevichvl** [petrovvlad/freeLib#169]
На KDE plasma 6.2.1 получаю следующую ошибку при запауске freelib 6.1.0-2:

```
freelib: symbol lookup error: freelib: undefined symbol: _ZN19QHttpServerResponse9addHeaderEO10QByteArrayS1_, version Qt_6
```
Устанавливал из AUR, пакет `freelib`.

При установке пакета `freelib-git` получается другая ошибка:

```
/home/vladimir/.cache/yay/freelib-git/src/freeLib/src/opds_server.cpp:776:12: error: ‘class QHttpServerResponse’ has no member named ‘addHeader’
```

`freelib-dev-git` - не устанавливается на этапе клона с гитхаба.
UPD: после смены сети удалось решить проблему, удалось поставить `freelib-dev-git` и все работает.

**Comment by petrovvlad** [comment]
Причина обновление Qt до 6.8. Частично проблема решена в 6.1.17. Пока некорректно работает opds/web сервер.

**Comment by petrovvlad** [comment]
Исправил 1157ee4.
