### ISSUE TITLE
Не сохраняется изменение шрифтов.

### ISSUE THREAD

**Issue by NovomirK** [petrovvlad/freeLib#171]
Kubuntu 24.04, версия программы 6.1.21

В настройках убираю галочку с Использовать системные шрифты, ставлю свои размеры, а настройки не сохраняются. При следующем запуске галка на месте.

**Comment by NovomirK** [comment]
Подождать новой версии программы? Или как-то могу исправить у себя?

**Comment by petrovvlad** [comment]
Как Вы устанавливали программу?

**Comment by NovomirK** [comment]
Из исходников. Вчера. По инструкции.

**Comment by NovomirK** [comment]
Скачал, пересобрал, шрифты всё так же не меняются. 
Вот так устанавливал:

Скачать исходники программы:

git clone --recurse-submodules https://github.com/petrovvlad/freeLib.git

Собрать и установить:

mkdir freeLib/build && cd freeLib/build && \
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. && cmake --build . -j2 && \
sudo cmake --install . --config Release

**Comment by NovomirK** [comment]
freeLib - Версия 6.1.21
Ревизия: e37b2af

Qt 5.15.13
Режим отладки отключен.
OPDS/Web сервер: нет

Операционная система: Ubuntu 24.04.1 LTS
Архитектура ЦП: x86_64
Ядро: linux 6.8.0-48-generic

**Comment by petrovvlad** [comment]
Текущая версия 6.1.25. У Вас, по какой-то причине не обновилась программа.

**Comment by NovomirK** [comment]
Пересобрал. Установилась версия 6.1.25. , в которой всё работет и проблемы со шрифтами нет. Спасибо Вам огромное за прекрасную программу и за поддержку!
