### ISSUE TITLE
поиск по имени файла

### ISSUE THREAD

**Issue by Balamoote** [petrovvlad/freeLib#174]
Просьба добавить в окно "Поиск" возможность поиска по имени файла.

**Comment by petrovvlad** [comment]
Если книга в архиве, искать по имени архива или файла в архиве?

**Comment by Balamoote** [comment]
Конечно имени файла в архиве. Можно где-то добавить опцию, где указывать что именно ищем... но это лишнее.

**Comment by petrovvlad** [comment]
Попробую.

**Comment by Balamoote** [comment]
Регистрозависимость разве что опциональная. По аналогии, команду locate без ключа -i я не думаю, что когда-либо использовал.

**Comment by petrovvlad** [comment]
Добавил поиск.
