### ISSUE TITLE
Конфликт "национального алфавита" с "фильтрами"

### ISSUE THREAD

**Issue by Balamoote** [petrovvlad/freeLib#182]
При выбранной опции "национальный алфавит", в окне поиска "Автор" принудительно выставляется первая буква алфавита. Если одновременно выбран один из фильтров, то он показывает только, в данном случае, то, что начинается на "А".
Нужно сделать поведение национального алфавита аналогичным дефолтному - английскому, где первым символом идет "*"

_EDIT: то же самое для "Серии"_

**Comment by petrovvlad** [comment]
Не вижу конфликта фильтра по Автору/Серии и фильтра по метке. 
В окне поиска по автору по умолчанию выставляется первый символ в первом ряду. Для национального алфавита «А», если национальный алфавит не выбран то «*».

**Comment by Balamoote** [comment]
Тогда, по итогам вопрос снимается. Но просьма рассказать, как правильно добавить "*" в список национального алфавита. Если просто добавить в abc_ru.txt, то всё отображается и работает корректно, но в конце появляется кнопка с пробелом. Совсем мелочь, но некрасиво...
