### ISSUE TITLE
Building and linking quazip

### ISSUE THREAD

**Issue by shnaps** [petrovvlad/freeLib#23]
There is a problem with the quazip when building freelib: it missing a couple files from zlib. And even adding them brings a lot more problems. Can you update instructions/config file regarding it?

**Comment by petrovvlad** [comment]
Did you clone freeLib with --recurse-submodules?

**Comment by shnaps** [comment]
Yes, I cloned it with submodules. And having problems copiling it. Freelib is fine.

**Comment by petrovvlad** [comment]
I compile in qt creator on linux without errors. What errors do you have when compiling. What version of qt?

**Comment by shnaps** [comment]
I'm trying to compile all the stuff on windows 10. QT Creater 4.11.1, QT 5.14.1, MSVC 2017.

And for error - when I compile project, error is 
>D:\QT\freeLib\freeLib\src\quazip\quazip\zip.h:56: error: C1083: Cannot open include file: 'zlib.h': No such file or directory

Seems like I'm missing some sources for quazip submodile and I think there should be the way to define them without reconfiguring.

**Comment by petrovvlad** [comment]
Looks like  this [https://github.com/stachenov/quazip/issues/11](). I don't have windows. I don't know how to install zlib.

**Comment by shnaps** [comment]
It can be. I already created an issue for this. There is a chance that I'll get updated instructions for windows.
But still, I'm not sure if it fill fix things, because freelib explicitly importing and using quazip sources. Can you consider moving to diiferent model of use?
