### ISSUE TITLE
Некорректная работа с zip-архивами

### ISSUE THREAD

**Issue by nnd31** [petrovvlad/freeLib#24]
Скомпилировал Вашу freeLib 5.0 на Ubunty 18.04  ( Исходники отсюда: http://sourceforge.net/projects/freelibdesign/files/5.0/freeLib5.0_source.zip
собралось хорошо, без ошибок.)
Создаю библиотеку ( сканирую каталог с книгами, файла INPX нет )
Если файлы с книгами *.fb2  - все работает как с латиницей так и с кирилицей в имени файлов.
Если *.zip или *.fb2.zip и при этом в архиве одиночный файл - тоже все в порядке.
Но если в архиве несколько файлов с кирилическими именами - происходит следующее:
В базу данных книги прописываются правильно, но открыть можно только одну из всего архива.
Ту, которая идет последней в выводе команды zipinfo. 
На всех прочих - ошибка открытия. При этом в /tmp/freeLib образуется файл с соответствующим книге именем, но он нулевой длины.
Если сама freeLib была запущена из консоли - то там видно такое:

QuaZipFile::open(): zip does not have current file
Error open file:  "Sum/Уайзмен - Фабиола.fb2"
QIODevice::read (QuaZipFile): device not open
QuaZipFile::close(): file isn't open
2020/08/07 12:07:24.6751 WARN Changing log level from 3 to 1

Сам zip либо fb2-файлы вне подозрений. Архив зазворачивается и тестируется нормально. Если файлы переименовать в транслит - все работает.

Надеюсь эта информация будет Вам полезна.

**Comment by petrovvlad** [comment]
Исправил. Проверьте в develop ветке.

**Comment by nnd31** [comment]
> Исправил. Проверьте в develop ветке.
  В exportthread.cpp  в строке 444 описка: arg(book.nFile).arg(book.sFormat);
                                                                                      ^~ надо "sFile"  ( это не я умный. Это компилятор сказал  ;-))
После исправления компиляция запустилать, и доходит без ошибок почти до конца. Но все-ж вываливается с таким сообщением:
quaadler32.o: In function `QuaAdler32::QuaAdler32()':
quaadler32.cpp:(.text+0xba): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quaadler32.o: In function `QuaAdler32::~QuaAdler32()':
quaadler32.cpp:(.text._ZN10QuaAdler32D2Ev[_ZN10QuaAdler32D5Ev]+0xf): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quaadler32.o: In function `QuaAdler32::~QuaAdler32()':
quaadler32.cpp:(.text._ZN10QuaAdler32D0Ev[_ZN10QuaAdler32D5Ev]+0x13): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quaadler32.o:(.data.rel.ro._ZTI10QuaAdler32[_ZTI10QuaAdler32]+0x10): undefined reference to `typeinfo for QuaChecksum32'
quacrc32.o: In function `QuaCrc32::QuaCrc32()':
quacrc32.cpp:(.text+0xba): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quacrc32.o: In function `QuaCrc32::~QuaCrc32()':
quacrc32.cpp:(.text._ZN8QuaCrc32D2Ev[_ZN8QuaCrc32D5Ev]+0xf): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quacrc32.o: In function `QuaCrc32::~QuaCrc32()':
quacrc32.cpp:(.text._ZN8QuaCrc32D0Ev[_ZN8QuaCrc32D5Ev]+0x13): undefined reference to `QuaChecksum32::~QuaChecksum32()'
quacrc32.o:(.data.rel.ro._ZTI8QuaCrc32[_ZTI8QuaCrc32]+0x10): undefined reference to `typeinfo for QuaChecksum32'
collect2: error: ld returned 1 exit status
Makefile:493: recipe for target 'freeLib' failed
make[1]: *** [freeLib] Error 1
make[1]: выход из каталога «/usr/local/src/freeLib-develop/freeLib/src»
Makefile:50: recipe for target 'sub-src-all-ordered' failed
make: *** [sub-src-all-ordered] Error 2

**Comment by petrovvlad** [comment]
exportthread.cpp поправил.
Что у вас изменилось? Раньше же компилировалось без ошибок.

**Comment by nnd31** [comment]
> exportthread.cpp поправил.
> Что у вас изменилось? Раньше же компилировалось без ошибок.
Раньше была qt5.9.5   С ней не собиралось, ругалось на "Project ERROR: Unknown module(s) in QT: webenginewidgets".  Сейчас стоит qt5.12.0-1

**Comment by petrovvlad** [comment]
только что собрал в Qt 5.12.2 без ошибок. 
Можете выложить лог полной сборки?

**Comment by nnd31** [comment]
> только что собрал в Qt 5.12.2 без ошибок.
> Можете выложить лог полной сборки?
Да, конечно. А куда кидать ? Прямо сюда ? Там файл 123Kб,  251 строка. Могу отправить на E-mail  или куда скажете ( контакт, чтобы здесь не светить, можете выслать на nic@satel.net.ua ). И сообщите какой лог лучше прислать ( с включенной отладкой или нет ) Нужен ли лог старой сборки ?

**Comment by petrovvlad** [comment]
Обновил quazip. Проверьте.

**Comment by nnd31** [comment]
> Обновил quazip. Проверьте.

Все прекрасно собирается и работает, если в файлах    build_number.sh  и   src.pro исправить "../../freeLib/src/build_number.h"  на  "../../../freeLib/src/build_number.h"
 В противном случае если запускать "qmake Lib_linux.pro"  из каталога ...freeLib/freeLib,  - останавливается на
cp: '/usr/local/src/freeLib-6.0.10/freeLib/src/xsl' и '/usr/local/src/freeLib-6.0.10/freeLib/src/xsl' - один и тот же файл
Makefile:502: recipe for target 'freeLib' failed
make[1]: *** [freeLib] Error 1

Если создать "build" и из него запускать "qmake ../Lib_linux.pro"  - без вышеназванных исправлений не находит build_number.sh 
Проверялась версия 6.0.14  под Ubuntu 18.04  QT5.14
