### ISSUE TITLE
Проблема с передачей параметров утилитам постобработки

### ISSUE THREAD

**Issue by nnd31** [petrovvlad/freeLib#26]
Утилитам постобработки передаются не все параметры:
Не передаются вовсе (т.е передаются пустые значения) параметрам  %nl,  %nm,  %nf
Вместо нужной буквы передается "." (  точка )  параметрам   %li,  %fi,  %mi. 

P.S.  IMHO параметры "%li,  %fi,  %mi " не особо и нужны. Разработчики утилит постобработки легко получат их значения сами из %nl,  %nm,  %nf.   Вот если-б вместо них передавались book-id, author-id ' -  было-бы полезно. Как минимум  мне  ;-))

**Comment by petrovvlad** [comment]
Поправил. Проверьте. 
book-id и author-id пока не добавлял.

**Comment by nnd31** [comment]
Параметры передаются корректно.
