### ISSUE TITLE
error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by DaarkWel** [petrovvlad/freeLib#27]
I'm trying to build freelib with qmake in Archlinux and I'm getting this error:

    In file included from mainwindow.cpp:18:
    SmtpClient/smtpclient.h:145:28: error: ISO C++17 does not allow dynamic exception specifications
      145 |     void waitForResponse() throw (ResponseTimeoutException);
          |                            ^~~~~
    mainwindow.cpp: In function 'QFileInfo GetBookFile(QBuffer&, QBuffer&, uint, bool, QDateTime*)':
    mainwindow.cpp:66:34: warning: 'QDateTime QFileInfo::created() const' is deprecated: Use either birthTime() or metadataChangeTime() [-Wdeprecated-declarations]
       66 |             *file_data=fi.created();
          |                        ~~~~~~~~~~^~
    In file included from /usr/include/qt/QtCore/qdir.h:44,
                     from /usr/include/qt/QtCore/QtCore:70,
                     from /usr/include/qt/QtSql/QtSqlDepends:3,
                     from /usr/include/qt/QtSql/QtSql:3,
                     from mainwindow.cpp:1:
    /usr/include/qt/QtCore/qfileinfo.h:139:15: note: declared here
      139 |     QDateTime created() const;
          |               ^~~~~~~
    mainwindow.cpp: In member function 'void MainWindow::BookDblClick()':
    mainwindow.cpp:961:13: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
      961 |             if(
          |             ^~
    mainwindow.cpp:970:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
      970 |                 return;
          |                 ^~~~~~
    make[1]: *** [Makefile:1271: mainwindow.o] Error 1
    make[1]: Leaving directory '/build/freeLib/freeLib/src'
    make: *** [Makefile:47: sub-src-make_first-ordered] Error 2

**Comment by petrovvlad** [comment]
ab6340a863519dabcbf670f9a74a83bf0608cd5c **delete SmtpClient**

**Comment by petrovvlad** [comment]
32e0a560d3a5a1bc384c6ca71539cf5629be1e71 **add submodule bluetiger9/SmtpClient-for-Qt**

**Comment by petrovvlad** [comment]
9bfe1c423d1eb9c86588e48938756ae2b380b452 **changes for submodule SmtpClient**

**Comment by petrovvlad** [comment]
fix.
