### ISSUE TITLE
Issue with extracting books

### ISSUE THREAD

**Issue by wombat2003** [petrovvlad/freeLib#31]
First of all many thanks for updating the program. 
Kubuntu 21
FreeLib works great but fails to extract files from the archive
It creates folders and subfolders, but fails to put the book there

**Comment by petrovvlad** [comment]
Which version are you using?

**Comment by wombat2003** [comment]
Последнюю с гита. Которая была в Deb. 6.0.1. работает все кроме выгрузки
самих книг.

чт, 25 нояб. 2021 г., 15:58 Vlad Petrov ***@***.***>:

**Comment by petrovvlad** [comment]
Ошибка с архивами была исправлена: ab542c072be2e6639342474d9b1c752d53930bef. Версия 6.0.11 должна работать. Если можете, соберите сами. До инструкции по сборке пока руки не дошли. Постараюсь выпустить, но пока не знаю когда.

**Comment by wombat2003** [comment]
Увы, без инструкции не соберу. Но все равно спасибо

**Comment by petrovvlad** [comment]
Добавил инструкцию для сборки в Ubuntu. Проверьте.

**Comment by wombat2003** [comment]
Да все работает. Спасибо

**Comment by wombat2003** [comment]
Выгрузка книг заработала корректно.
