### ISSUE TITLE
Невозможно заполнить данные бибилотеки при первом добавлении

### ISSUE THREAD

**Issue by wombat2003** [petrovvlad/freeLib#39]
При добавлении библиотеки (нажимаем +) все поля неактивны. Приходится закрывать диалог и открывать заново. В этом случае можно заполнить остальные поля
![Screenshot_20211213_081153](https://user-images.githubusercontent.com/33647464/145756401-73c75319-ffbc-4721-9431-4cb7a621acdd.png)

**Comment by petrovvlad** [comment]
9925ea34b4ed00e6dd676f9612e560ff6f17327c Исправил. Проверьте.

**Comment by wombat2003** [comment]
Да теперь нормально
