### ISSUE TITLE
Фантомные библиотеки в списке

### ISSUE THREAD

**Issue by wombat2003** [petrovvlad/freeLib#40]
Библиотеки удалены и кнопка "-" неактивна в диалоге управления библиотеками. Нов списке они есть по прежнему

![Screenshot_20211213_081413](https://user-images.githubusercontent.com/33647464/145756451-dc8a7829-7899-4ff3-995a-5bcaffb9a746.png)

**Comment by petrovvlad** [comment]
9925ea34b4ed00e6dd676f9612e560ff6f17327c Исправил. Проверьте.

**Comment by wombat2003** [comment]
Исправлено
