### ISSUE TITLE
При создании нового профиля утилит постобработки сохраняются не все параметры

### ISSUE THREAD

**Issue by nnd31** [petrovvlad/freeLib#45]
В разделе "Насторойки" "Утилиты постобрабртки"  добавляю свою утилиту ( добавляется нормально)
В  раздел "Экспорт" добавляю новый профиль, и в его настройках в секции "Экспорт" "Постобработка" указываю свою утилиту. Все нормально работает до перезапуска freeLib.  После перезапуска новый профиль на месте, но в его настройках  в секции "Экспорт"  параметр "Постобработка" не сохраняется ( стоит "ничего не делать"  вместо утилиты )

**Comment by petrovvlad** [comment]
02a851a9035baf328890b5dd0e4947c4b1d220fe Исправил. Проверьте.

**Comment by nnd31** [comment]
Все в порядке. Настройки сохраняются
