### ISSUE TITLE
Некорректная работа с файлами *.fb2

### ISSUE THREAD

**Issue by nnd31** [petrovvlad/freeLib#48]
freeLib  6.0.17, Ubuntu 20.04.
Создаю библиотеку. Книги в каталоге отдельными файлами. inpx нет. Часть книг заархивированы ( *.fb2.zip).  С ними все нормально.  Часть нет ( *.fb2 ).  Эти не экспортируются и не открываются ридером.

**Comment by wombat2003** [comment]
Подтверждаю. Папка с чистыми fb2 добавляется в бибилиотеку нормально, но да - не эк портируются  не открываются книги

**Comment by petrovvlad** [comment]
663f1a989cce6d4b0aa03eb9af99e5333b8aabd5 Исправил. Проверяйте :).

**Comment by wombat2003** [comment]
Заработало
