### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by NovomirK** [petrovvlad/freeLib#76]
Добрый день. Когда ищешь автора, в закладке поиск, обязательно первой должна идти фамилия, иначе не находит. Это баг или фича?

**Comment by petrovvlad** [comment]
Пока это фича :). Но можно попробовать усложнить алгоритм поиска.

**Comment by NovomirK** [comment]
Если когда-нибудь руки дойдут, то, вероятно ,будет удобнее искать.

**Comment by petrovvlad** [comment]
Что-то сделал. Попробуйте.

**Comment by NovomirK** [comment]
Не вижк изменений. Ставлю первым имя и не находит. К примеру Скотт Вальтер находит, а Вальтер Скотт нет.

**Comment by petrovvlad** [comment]
Изменения пока только в develop ветке.

**Comment by NovomirK** [comment]
Так из неё и поставил. Версия 6.0.32.

**Comment by petrovvlad** [comment]
Я вижу в develop 6.0.33

**Comment by NovomirK** [comment]
Сейчас попробую ещё раз.

**Comment by NovomirK** [comment]
У меня 6.0.32 ставится. Проверьте, пожалуйста, верно ли делаю:
`git clone --recurse-submodules -b develop https://github.com/petrovvlad/freeLib.git
mkdir freeLib/build && cd freeLib/build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. && cmake --build . -j2
`

**Comment by petrovvlad** [comment]
Да всё правильно. Только, что проверил на виртуальной машине, у меня собирается 6.0.33. Собирается без ошибок?

**Comment by NovomirK** [comment]
Опять переустановил. Старая версия. По-моему без:

-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- The C compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using Qt version 5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ronin/freeLib/build
Scanning dependencies of target QuaZip_autogen
[  1%] Automatic MOC and UIC for target QuaZip
[  1%] Built target QuaZip_autogen
Scanning dependencies of target QuaZip
[  3%] Building C object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/unzip.c.o
[  4%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/QuaZip_autogen/mocs_compilation.cpp.o
[  6%] Building C object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/zip.c.o
[  8%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/JlCompress.cpp.o
[  9%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/qioapi.cpp.o
[ 11%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quaadler32.cpp.o
[ 13%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quachecksum32.cpp.o
[ 14%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quacrc32.cpp.o
[ 16%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quagzipfile.cpp.o
[ 18%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quaziodevice.cpp.o
[ 19%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quazip.cpp.o
[ 21%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quazipdir.cpp.o
[ 22%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quazipfile.cpp.o
[ 24%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quazipfileinfo.cpp.o
[ 26%] Building CXX object freeLib/src/quazip/quazip/CMakeFiles/QuaZip.dir/quazipnewinfo.cpp.o
[ 27%] Linking CXX static library libquazip1-qt5.a
[ 27%] Built target QuaZip
Scanning dependencies of target freelib_autogen
[ 29%] Automatic MOC and UIC for target freelib
[ 29%] Built target freelib_autogen
[ 31%] Generating qrc_resource.cpp
Scanning dependencies of target freelib
[ 32%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/main.cpp.o
[ 34%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/freelib_autogen/mocs_compilation.cpp.o
[ 36%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/mainwindow.cpp.o
[ 37%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/library.cpp.o
[ 39%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/librariesdlg.cpp.o
[ 40%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/settingsdlg.cpp.o
[ 42%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/exportframe.cpp.o
[ 44%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/fontframe.cpp.o
[ 45%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/exportdlg.cpp.o
[ 47%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/aboutdialog.cpp.o
[ 49%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/helpdialog.cpp.o
[ 50%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/tagdialog.cpp.o
[ 52%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/bookeditdlg.cpp.o
[ 54%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/importthread.cpp.o
[ 55%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/exportthread.cpp.o
[ 57%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/opds_server.cpp.o
[ 59%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/options.cpp.o
[ 60%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/treebookitem.cpp.o
[ 62%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/coverlabel.cpp.o
[ 63%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/starsdelegate.cpp.o
[ 65%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/utilites.cpp.o
[ 67%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/genresortfilterproxymodel.cpp.o
[ 68%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/fb2mobi/hyphenations.cpp.o
[ 70%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/fb2mobi/fb2mobi.cpp.o
[ 72%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/mobiEdit/mobiedit.cpp.o
[ 73%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/emailaddress.cpp.o
[ 75%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimeattachment.cpp.o
[ 77%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimecontentformatter.cpp.o
[ 78%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimefile.cpp.o
[ 80%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimemessage.cpp.o
[ 81%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimemultipart.cpp.o
[ 83%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimepart.cpp.o
[ 85%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimetext.cpp.o
[ 86%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/quotedprintable.cpp.o
[ 88%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/smtpclient.cpp.o
[ 90%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimebase64encoder.cpp.o
[ 91%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimebase64formatter.cpp.o
[ 93%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimeqpformatter.cpp.o
[ 95%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimeqpencoder.cpp.o
[ 96%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/SmtpClient/src/mimecontentencoder.cpp.o
[ 98%] Building CXX object freeLib/src/CMakeFiles/freelib.dir/qrc_resource.cpp.o
[100%] Linking CXX executable freelib
[100%] Built target freelib

**Comment by petrovvlad** [comment]
выполняли `sudo make install` ?

**Comment by NovomirK** [comment]
Нет. Все под инструкции. Я и раньше не выполнял и все ставились.

**Comment by petrovvlad** [comment]
Так в инструкции есть `sudo make install`. Как вы запускаете программу?

**Comment by NovomirK** [comment]
Так. Вчера поздно было и устал я. Сегодня постараюсь устать меньше и сделать внимательнее.

**Comment by NovomirK** [comment]
Прошу прощения. Это меня вчера переклинило. Всё установилось и заработало.

**Comment by petrovvlad** [comment]
Если работает так как хотели, можете закрыть issue.
