### ISSUE TITLE
Зависание в табличном режиме

### ISSUE THREAD

**Issue by NovomirK** [petrovvlad/freeLib#79]
Добрый день. В табличном режиме, когда отправляешь книги на 1 аккаунт, то всё хорошо. Когда пытаешься отправить на второй программа зависает и ни на что не реагирует. В обычном режиме (древовидном) всё в порядке. Заметил подобное на версиях 3.0.33 и 3.0.66. на иных не пробовал.

**Comment by petrovvlad** [comment]
Не получается воспроизвести ошибку. Поэтому расскажите подробнее. Вы отправляете на разные аккаунты? Зависание происходит только когда вы отправляете 2 аккаунт? Происходят ли зависания при первой отправке или при повторной?

**Comment by NovomirK** [comment]
Да на разные аккаунты kindle. Почему-то именно в табличном режиме случается. 
 Ещё чувство, что временами не отправляется вообще, в табличном режиме. Но я не могу воспроизвести когда и после чего. Просто вижу, что я эту книгу отправлял, но ее нет, а следующая есть. Не могу уловить логику событий.

**Comment by petrovvlad** [comment]
Есть ли зависимость от аккаунта на который отправляете? 
Есть ли зависимость от размера книги? 
Отправляете по одной книге или несколько за раз?

**Comment by NovomirK** [comment]
Вне зависимости от аккаунта. Вчера даже специально создал новый способ отправки на аккаунт. Отправляю epub может быть причина в конвертере? Запускал через консоль, но там ошибок не видно было. Просто висит окно отправки и не закрывается и  программа не закрывается

**Comment by petrovvlad** [comment]
В настройках email, какой тип соединения (tcp, ssl, tcl)?

**Comment by NovomirK** [comment]
SSL. 
Ещё есть подозрение, что отправка через gmail не работает. Вероятно, из-за двухфакторной аутентификации. Но, это ещё не доказано.

**Comment by petrovvlad** [comment]
Я проверял на яндексе с паролем приложения, может поэтому. Можете проверить на яндексе?

**Comment by NovomirK** [comment]
На Яндексе точно все хорошо. У меня через него на 3 аккаунта пересылает без проблем.

**Comment by NovomirK** [comment]
сейчас гонял программу "в хвост и в гриву", но вчерашнего бага поймать не смог. И на разные аккаунты слал и режимы переключал, всё работает. Вчера раза 4 подряд зависала. Не знаю что и думать. 
Единственное, книги не приходят, если указать gmail, но нужно ещё другой ящик попробовать. Сегодня уже не успею.

**Comment by NovomirK** [comment]
И опять прогнал и не смог поймать баг. Если Вы не против, пока закрывать тему не буду. Попытаюсь воспроизвести.

**Comment by NovomirK** [comment]
Не смог воспроизвести. Вероятно, глюк моей системы. Прошу прощения.
