### ISSUE TITLE
Не устанавливается в ubuntu 22.04

### ISSUE THREAD

**Issue by gru05** [petrovvlad/freeLib#80]
Добрый день.
Выполнении команды:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. && cmake --build . -j2`
завершается ошибкой.

![screenshot](https://user-images.githubusercontent.com/106838361/171936667-dc7c8bd9-3981-4895-b1bc-d13a02234244.png)

Система Ubuntu 22.04
Делал все по инструкции.
Подскажите в какую сторону копать.

**Comment by gru05** [comment]
Удалил строку 

`#include "QtWebEngineWidgets/qwebenginepage.h"
в файле 
freeLib/freeLib/src/fb2mobi/fb2mobi.cpp`

и все установилось и даже работает.

**Comment by petrovvlad** [comment]
Спасибо.
