### ISSUE TITLE
sudo в cmakelists

### ISSUE THREAD

**Issue by DaarkWel** [petrovvlad/freeLib#83]
Ставлю freelib в арчлинукс, через этот PKGBUILD: https://aur.archlinux.org/packages/freelib-git
После сборки запрашивается лишний раз пароль sudo, из-за этой строчки в исходниках:

`execute_process(COMMAND sudo gtk-update-icon-cache ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}/icons/hicolor)`

Насколько я понимаю, обновление кэша значков лучше оставить пакетному менеджеру. Я, конечно, могу написать патч в PKGBUILD, который будет удалять эту строчку, но нужна ли она в принципе?

**Comment by petrovvlad** [comment]
Я её добавил потому, что после `sudo make install`, в на виртуальной машине Ubuntu программа не появлялась в меню приложений. Я соглашусь с вами, этой команде не место в cmakelists.

**Comment by DaarkWel** [comment]
Отлично, спасибо.
